spring:
  application:
    name: poc-rabbitmq-publisher
  rabbitmq:
    port: 5672
    host: localhost
    username: admin
    password: test

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        includ: "*"
